spring.application.name=BookStore
# 1. Thông tin k?t n?i (Thay 'BookstoreDB' b?ng tên DB b?n t?o trong SSMS)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookstoreDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
#spring.datasource.password=123456
#Scu
spring.datasource.password=123

# 2. Driver và Dialect dành riêng cho SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. T? ??ng t?o b?ng t? Code Java (R?t ti?n cho ?? án nhóm)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true